const SERVERIP = '127.0.0.1';
const SERVERPORT ='3000';
export const SERVERADDRESS = 'http://'+SERVERIP +':'+ SERVERPORT;

export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const SETTINGINFO = 'SETTINGINFO'; //设置个人信息
export const GETTINGINFO = 'GETTINGINFO'; //获取个人信息
export const GETUSERID = 'GETUSERID'; // 获取用户uid
export const DELCOMMENT = 'DELCOMMENT'; // 删除评论
export const FOCUS = 'FOCUS'; // 关注
export const LOGIN = 'LOGIN';  // 登录
export const LOGOUT = 'LOGOUT';//登出
export const NOLOGIN = 'NOLOGIN';//未登录
export const REGISTER = 'REGISTER'; //注册成功
export const SHOWMODAL = 'SHOWMODAL'; // 展示弹窗
export const HIDEMODAL = 'HIDEMODAL' ;//关闭弹窗
export const UPDATETOPICLIST = 'UPDATETOPICLIST'; // 获取所有的文章列表
export const GETAUTHORDETAIL = 'GETAUTHORDETAIL'; // 获取作者详情
export const GETBANNERLIST = 'GETBANNERLIST'; //获取banner列表
export const ADDTOPIC = 'ADDTOPIC';       //添加新文章
export const ADDCOMMENT = 'ADDCOMMENT';  //添加新评论
export const UPLOADPIC = 'UPLOADPIC';  //头像图片上传
export const UPDATEUSERINFO	= 'UPDATEUSERINFO';
export const CHANGESIDERCURRENT	= 'CHANGESIDERCURRENT';
export const CHANGEPAGENO = 'CHANGEPAGENO';  // 分页
export const NOMOREDATA = 'NOMOREDATA';  // 没有更多数据了
export const CHANGEPAGESIZE = 'CHANGEPAGESIZE';
export const CHANGEPAGETOTAL = 'CHANGEPAGETOTAL';
export const UPDATEPOSTERINFO = 'UPDATEPOSTERINFO';
export const UPDATEDETAILINFO = 'UPDATEDETAILINFO'; //更新文章详情
export const UPDATECOMMENTLIST = 'UPDATECOMMENTLIST'; //获取文章评论列表
export const UPDATECATEGORYDATA = 'UPDATECATEGORYDATA';
export const UPDATEPOSTNODATA = 'UPDATEPOSTNODATA';
