const SERVERIP = '127.0.0.1';
const SERVERPORT ='3000';
export const SERVERADDRESS = 'http://'+SERVERIP +':'+ SERVERPORT;

export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const ISCOLLAPSE = 'ISCOLLAPSE';
export const ISNOTCOLLAPSE = 'ISNOTCOLLAPSE';
export const LOGIN = 'LOGIN';  // 登录
export const LOGOUT = 'LOGOUT';//登出
export const REGISTER = 'REGISTER'; //注册成功
export const SHOWMODAL = 'SHOWMODAL'; // 展示弹窗
export const HIDEMODAL = 'HIDEMODAL' ;//关闭弹窗
export const UPDATETOPICLIST = 'UPDATETOPICLIST'; // 获取所有的文章列表
export const GETBANNERLIST = 'GETBANNERLIST'; //获取banner列表
export const ADDTOPIC = 'ADDTOPIC';       //添加新文章
export const ADDCOMMENT = 'ADDCOMMENT';  //添加新评论
export const UPDATEUSERINFO	= 'UPDATEUSERINFO';
export const CHANGESIDERCURRENT	= 'CHANGESIDERCURRENT';
export const CHANGEPAGENO = 'CHANGEPAGENO';  // 分页
export const NOMOREDATA = 'NOMOREDATA';  // 没有更多数据了
export const CHANGEPAGESIZE = 'CHANGEPAGESIZE';
export const CHANGEPAGETOTAL = 'CHANGEPAGETOTAL';
export const UPDATEPOSTERINFO = 'UPDATEPOSTERINFO';
export const UPDATEDETAILINFO = 'UPDATEDETAILINFO'; //更新文章详情
export const UPDATECOMMENTLIST = 'UPDATECOMMENTLIST'; //获取文章评论列表
export const UPDATECATEGORYDATA = 'UPDATECATEGORYDATA';
export const UPDATEPOSTNODATA = 'UPDATEPOSTNODATA';
